# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_2.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1100, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1100, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1100, 600))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setItalic(False)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 480, 811, 67))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.download_file = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.download_file.setFont(font)
        self.download_file.setText("")
        self.download_file.setObjectName("download_file")
        self.verticalLayout.addWidget(self.download_file)
        self.download_process = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setItalic(True)
        self.download_process.setFont(font)
        self.download_process.setText("")
        self.download_process.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.download_process.setObjectName("download_process")
        self.verticalLayout.addWidget(self.download_process)
        self.progressBar = QtWidgets.QProgressBar(self.layoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(140, 170, 861, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_2.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(208, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        spacerItem1 = QtWidgets.QSpacerItem(208, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_2.addWidget(self.label_7)
        self.download_btn = QtWidgets.QPushButton(self.centralwidget)
        self.download_btn.setEnabled(True)
        self.download_btn.setGeometry(QtCore.QRect(400, 430, 261, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.download_btn.setFont(font)
        self.download_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.download_btn.setCheckable(False)
        self.download_btn.setObjectName("download_btn")
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 200, 1081, 221))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.module_soft_list = QtWidgets.QListWidget(self.layoutWidget2)
        self.module_soft_list.setMinimumSize(QtCore.QSize(340, 200))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.module_soft_list.setFont(font)
        self.module_soft_list.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.module_soft_list.setAutoFillBackground(False)
        self.module_soft_list.setObjectName("module_soft_list")
        self.horizontalLayout_3.addWidget(self.module_soft_list)
        spacerItem2 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.oqc_soft_list = QtWidgets.QListWidget(self.layoutWidget2)
        self.oqc_soft_list.setMinimumSize(QtCore.QSize(340, 200))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setItalic(False)
        self.oqc_soft_list.setFont(font)
        self.oqc_soft_list.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.oqc_soft_list.setObjectName("oqc_soft_list")
        self.horizontalLayout_3.addWidget(self.oqc_soft_list)
        spacerItem3 = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.restart_soft_list = QtWidgets.QListWidget(self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.restart_soft_list.sizePolicy().hasHeightForWidth())
        self.restart_soft_list.setSizePolicy(sizePolicy)
        self.restart_soft_list.setMinimumSize(QtCore.QSize(340, 200))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setItalic(False)
        self.restart_soft_list.setFont(font)
        self.restart_soft_list.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.restart_soft_list.setObjectName("restart_soft_list")
        self.horizontalLayout_3.addWidget(self.restart_soft_list)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(240, 10, 631, 141))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setKerning(True)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.ip_1 = QtWidgets.QLineEdit(self.widget)
        self.ip_1.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ip_1.setFont(font)
        self.ip_1.setMaxLength(15)
        self.ip_1.setAlignment(QtCore.Qt.AlignCenter)
        self.ip_1.setObjectName("ip_1")
        self.gridLayout.addWidget(self.ip_1, 0, 1, 1, 1)
        self.search_module_btn = QtWidgets.QPushButton(self.widget)
        self.search_module_btn.setMinimumSize(QtCore.QSize(0, 35))
        self.search_module_btn.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        font.setItalic(False)
        self.search_module_btn.setFont(font)
        self.search_module_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search_module_btn.setObjectName("search_module_btn")
        self.gridLayout.addWidget(self.search_module_btn, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.module_name = QtWidgets.QLineEdit(self.widget)
        self.module_name.setEnabled(True)
        self.module_name.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.module_name.setFont(font)
        self.module_name.setText("")
        self.module_name.setObjectName("module_name")
        self.gridLayout.addWidget(self.module_name, 1, 1, 1, 1)
        self.link_ftp_btn = QtWidgets.QPushButton(self.widget)
        self.link_ftp_btn.setMinimumSize(QtCore.QSize(0, 35))
        self.link_ftp_btn.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        font.setItalic(False)
        self.link_ftp_btn.setFont(font)
        self.link_ftp_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.link_ftp_btn.setObjectName("link_ftp_btn")
        self.gridLayout.addWidget(self.link_ftp_btn, 0, 2, 1, 1)
        self.clear_btn = QtWidgets.QPushButton(self.widget)
        self.clear_btn.setMinimumSize(QtCore.QSize(0, 35))
        self.clear_btn.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.clear_btn.setFont(font)
        self.clear_btn.setObjectName("clear_btn")
        self.gridLayout.addWidget(self.clear_btn, 1, 3, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label_5.setBuddy(self.module_soft_list)
        self.label_6.setBuddy(self.oqc_soft_list)
        self.label_7.setBuddy(self.restart_soft_list)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.module_name, self.module_soft_list)
        MainWindow.setTabOrder(self.module_soft_list, self.restart_soft_list)
        MainWindow.setTabOrder(self.restart_soft_list, self.ip_1)
        MainWindow.setTabOrder(self.ip_1, self.link_ftp_btn)
        MainWindow.setTabOrder(self.link_ftp_btn, self.search_module_btn)
        MainWindow.setTabOrder(self.search_module_btn, self.download_btn)
        MainWindow.setTabOrder(self.download_btn, self.clear_btn)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_5.setText(_translate("MainWindow", "产线软件"))
        self.label_6.setText(_translate("MainWindow", "OQC 软件"))
        self.label_7.setText(_translate("MainWindow", "重工/返修软件"))
        self.download_btn.setText(_translate("MainWindow", "下载"))
        self.download_btn.setShortcut(_translate("MainWindow", "F3"))
        self.label_4.setText(_translate("MainWindow", "舜宇智能光学生产软件下载工具"))
        self.ip_1.setText(_translate("MainWindow", "10.16.33.20"))
        self.search_module_btn.setText(_translate("MainWindow", "搜索"))
        self.search_module_btn.setShortcut(_translate("MainWindow", "Return"))
        self.label_2.setText(_translate("MainWindow", "模组名称："))
        self.label.setText(_translate("MainWindow", "IP 地址："))
        self.module_name.setPlaceholderText(_translate("MainWindow", "请输入模组名称"))
        self.link_ftp_btn.setText(_translate("MainWindow", "连接"))
        self.link_ftp_btn.setShortcut(_translate("MainWindow", "F1"))
        self.clear_btn.setText(_translate("MainWindow", "清除"))
        self.clear_btn.setShortcut(_translate("MainWindow", "F2"))
